version: "3.7"

services:
  db:
    container_name: books_db
    image: postgres:14.3
    expose:
      - "5432"
    ports:
      - "5432:5432/tcp"
    environment:
      POSTGRES_USER: ${BOOKS_STORAGE_USER}
      POSTGRES_PASSWORD: ${BOOKS_STORAGE_PASSWORD}
      POSTGRES_DB: ${BOOKS_STORAGE_NAME}
    volumes: 
      - ./data/migrations/:/docker-entrypoint-initdb.d/:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U dev_local", "-d dev_local"]
  
  api:
    container_name: books_api
    build: .
    restart: always
    ports:
      - "8989:8989/tcp"
    environment:
      BOOKS_HTTPSERVER: ${BOOKS_HTTPSERVER}
      BOOKS_STORAGE_USER: ${BOOKS_STORAGE_USER}
      BOOKS_STORAGE_PASSWORD: ${BOOKS_STORAGE_PASSWORD}
      BOOKS_STORAGE_HOST: ${BOOKS_STORAGE_HOST}
      BOOKS_STORAGE_PORT: ${BOOKS_STORAGE_PORT}
      BOOKS_STORAGE_NAME: ${BOOKS_STORAGE_NAME}
      BOOKS_GOOGLE_API: ${BOOKS_GOOGLE_API}